"use client";

import { AlertTriangle, ArrowLeft, Bot, CheckCircle2, ChevronDown, Flame, LockKeyhole, Mic, Send, Sparkles, WandSparkles, X } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import Brand from "./Brand";

const generatedQuestions = [
  { type: "DIRECT CBSE PYQ", marks: "3 MARKS", year: "CBSE 2023", question: "An object is placed 20 cm in front of a concave mirror of focal length 15 cm. Find the position and nature of the image." },
  { type: "PYQ-BASED PATTERN", marks: "5 MARKS", year: "High probability", question: "A ray of light enters a rectangular glass slab. Draw the complete ray diagram and explain why the emergent ray is parallel to the incident ray." },
  { type: "DIRECT CBSE PYQ", marks: "2 MARKS", year: "CBSE 2020", question: "Define power of a lens. Calculate the power of a convex lens with focal length 25 cm." },
];

export default function ChapterDetail() {
  const [expanded, setExpanded] = useState(true);
  const [chat, setChat] = useState(false);
  const [generated, setGenerated] = useState(false);
  const [generating, setGenerating] = useState(false);
  const generateQuestions = () => {
    if (generated) { setGenerated(false); return; }
    setGenerating(true);
    window.setTimeout(() => { setGenerating(false); setGenerated(true); }, 1750);
  };
  return <main className="ambient min-h-screen bg-[#f5f7fc]">
    <header className="border-b border-slate-200 bg-white/85 backdrop-blur"><div className="mx-auto flex h-[70px] max-w-5xl items-center justify-between px-4 sm:px-6"><Brand/><Link href="/dashboard" className="text-xs font-black text-slate-500">Dashboard</Link></div></header>
    <div className="mx-auto max-w-5xl px-4 py-7 sm:px-6"><Link href="/dashboard" className="inline-flex items-center gap-1 text-xs font-bold text-slate-500"><ArrowLeft size={14}/> Back to chapters</Link>
      <section className="mt-5 rounded-[28px] bg-[#111827] p-6 text-white sm:p-8"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-white/10 px-3 py-1 text-[10px] font-black tracking-wider">SCIENCE · CLASS 10</span><span className="rounded-full bg-red-500/20 px-3 py-1 text-[10px] font-black text-red-300"><Flame size={11} className="mr-1 inline"/>98% HOT PICK</span></div><h1 className="mt-4 text-3xl font-black tracking-tight sm:text-4xl">Light — Reflection & Refraction</h1><p className="mt-2 text-sm text-slate-300">8 marks predicted · Based on 10 years of CBSE patterns</p><div className="mt-6 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full w-1/4 rounded-full bg-blue-400"/></div><p className="mt-2 text-xs font-bold text-slate-400">1 of 4 questions completed</p></section>
      <div className="mt-7 grid gap-6 lg:grid-cols-[1fr_290px]"><section><div className="flex items-center justify-between"><h2 className="text-xl font-black">Your high-yield 4</h2><span className="rounded-lg bg-green-100 px-2 py-1 text-[10px] font-black text-green-700">FREE PREVIEW</span></div>
        <article className="mt-4 overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><div className="flex justify-between gap-3"><span className="text-xs font-black text-blue-600">01 · SHORT ANSWER · 3 MARKS</span><span className="text-[10px] font-black text-slate-400">REPEATED 6×</span></div><h3 className="mt-3 text-lg font-black leading-7">State the laws of reflection of light. Draw a ray diagram for a concave mirror.</h3></div><button onClick={() => setExpanded(!expanded)} className="flex w-full items-center justify-between p-5 text-left text-sm font-black">{expanded ? "Hide mark-winning answer" : "Show mark-winning answer"}<ChevronDown className={expanded ? "rotate-180 transition" : "transition"} size={18}/></button>{expanded && <div className="border-t border-slate-100 bg-slate-50 p-5"><p className="text-xs font-black text-slate-400">STEP-BY-STEP MARKING RUBRIC</p><div className="mt-4 space-y-3">{["The angle of incidence is equal to the angle of reflection.", "The incident ray, reflected ray and normal all lie in the same plane.", "Draw the incident ray, normal and reflected ray with labels."].map((step, index) => <p key={step} className="flex gap-3 text-sm leading-5"><CheckCircle2 className="shrink-0 text-green-500" size={18}/><span>{step}<b className="ml-2 rounded bg-green-100 px-1.5 py-0.5 text-[10px] text-green-700">+{index === 2 ? "1" : "½"} mark</b></span></p>)}</div><div className="mt-5 flex gap-2 rounded-xl border border-red-100 bg-red-50 p-3 text-xs leading-5 text-red-800"><AlertTriangle className="shrink-0" size={17}/><span><b>Exam trap:</b> angles are always measured with the normal, never with the mirror.</span></div></div>}</article>
        <LockedQuestion number="02"/><LockedQuestion number="03"/>
        <div className="mt-4 rounded-2xl border border-dashed border-blue-200 bg-blue-50/60 p-5 text-center"><span className={`mx-auto grid size-10 place-items-center rounded-xl bg-white text-blue-600 shadow-sm ${generating ? "animate-pulse" : ""}`}><WandSparkles size={19}/></span><h3 className="mt-3 font-black">Need more practice?</h3><p className="mx-auto mt-1 max-w-sm text-xs leading-5 text-slate-500">Get fresh pattern-based questions plus direct questions pulled from CBSE PYQs.</p>{generating && <p className="mt-3 text-[11px] font-bold text-blue-600">Analysing 10-year PYQ patterns and marking schemes…</p>}<button disabled={generating} onClick={generateQuestions} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-xs font-black text-white shadow-lg shadow-blue-200 disabled:cursor-wait disabled:opacity-70"><WandSparkles className={generating ? "animate-spin" : ""} size={15}/>{generating ? "Generating your question set…" : generated ? "Hide generated questions" : "Generate more questions"}</button></div>
        {generated && <div className="mt-4 space-y-3"><div className="rounded-xl border border-violet-100 bg-violet-50 px-3 py-2 text-[11px] font-bold text-violet-700"><Sparkles className="mr-1 inline" size={13}/> AI set ready · 2 direct PYQs + 1 pattern-predicted question</div><div className="flex items-center gap-2"><Sparkles size={16} className="text-violet-600"/><h3 className="font-black">Fresh practice set</h3><span className="text-[10px] font-bold text-slate-400">3 generated just for you</span></div>{generatedQuestions.map((item, index) => <article key={item.question} className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center gap-2 text-[10px] font-black"><span className={item.type === "DIRECT CBSE PYQ" ? "rounded bg-rose-100 px-2 py-1 text-rose-600" : "rounded bg-violet-100 px-2 py-1 text-violet-600"}>{item.type}</span><span className="text-slate-400">Q{index + 5} · {item.marks} · {item.year}</span></div><h3 className="mt-3 text-sm font-black leading-6">{item.question}</h3></article>)}</div>}
      </section><aside className="rounded-[24px] bg-white p-5 shadow-sm"><span className="grid size-10 place-items-center rounded-xl bg-violet-100 text-violet-600"><Sparkles size={20}/></span><h2 className="mt-4 text-lg font-black">Doubt? Ask Bhai.</h2><p className="mt-1 text-xs leading-5 text-slate-500">No boring teacher talk. Get the trick, straight up.</p><div className="mt-4 space-y-2">{["Explain this proof like I’m 10", "Where do students lose marks?", "Give me the 1-line formula trick"].map(text => <button onClick={() => setChat(true)} className="w-full rounded-xl border border-slate-100 p-2.5 text-left text-[11px] font-bold text-slate-600 hover:border-violet-200" key={text}>{text}</button>)}</div><button onClick={() => setChat(true)} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-violet-600 py-3 text-xs font-black text-white"><Bot size={16}/> Ask anything</button></aside></div>
    </div>{chat && <Chat close={() => setChat(false)}/>}</main>;
}
function LockedQuestion({ number }: { number: string }) { return <div className="relative mt-3 overflow-hidden rounded-2xl border border-slate-100 bg-white p-5"><div className="opacity-25"><p className="text-xs font-black text-blue-600">{number} · LONG ANSWER · 5 MARKS</p><h3 className="mt-3 text-lg font-black">Derive the mirror formula and magnification relation.</h3><div className="mt-4 h-3 w-3/4 rounded bg-slate-200"/><div className="mt-3 h-3 w-1/2 rounded bg-slate-200"/></div><div className="absolute inset-0 grid place-items-center bg-white/20 backdrop-blur-[3px]"><span className="flex items-center gap-2 rounded-xl bg-[#171827] px-4 py-2.5 text-xs font-black text-white"><LockKeyhole size={15}/> Unlock with Crammer Pass</span></div></div>; }
function Chat({ close }: { close: () => void }) { return <div className="fixed inset-0 z-50 flex items-end justify-end bg-slate-950/20 p-3 sm:p-5"><div className="w-full max-w-sm overflow-hidden rounded-[24px] bg-white shadow-2xl"><div className="flex items-center justify-between bg-violet-600 p-4 text-white"><div className="flex items-center gap-2"><Bot size={21}/><span className="text-sm font-black">Bhai&apos;s got you</span></div><button onClick={close} aria-label="Close chat"><X size={18}/></button></div><div className="h-56 p-4"><p className="max-w-[85%] rounded-2xl rounded-tl-sm bg-violet-50 p-3 text-xs leading-5 text-slate-700">Bata bhai, reflection kaunsa part confusing lag raha hai? I&apos;ll make it easy.</p></div><div className="flex gap-2 border-t p-3"><button className="grid size-9 place-items-center rounded-lg bg-slate-100 text-slate-500"><Mic size={16}/></button><input className="min-w-0 flex-1 text-xs outline-none" placeholder="Ask your doubt..."/><button className="grid size-9 place-items-center rounded-lg bg-violet-600 text-white"><Send size={15}/></button></div></div></div>; }
