"use client";

import { ArrowRight, BookOpen, Bot, Check, ChevronRight, Flame, LockKeyhole, Sparkles, Trophy, X } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import Header from "./Header";

const subjects = [
  { name: "Mathematics", icon: "∑", chapters: 15, color: "bg-[#fff0ef] text-[#ef4444]", hot: "4 hot picks" },
  { name: "Science", icon: "⚗", chapters: 16, color: "bg-[#eafaf4] text-[#169b68]", hot: "6 hot picks" },
  { name: "Social Science", icon: "◎", chapters: 20, color: "bg-[#f0edff] text-[#7654e8]", hot: "3 hot picks" },
];
const chapters = [
  ["Light – Reflection & Refraction", "8 Marks", "98% Hot Pick", "bg-rose-50 text-rose-600", "bg-red-100 text-red-600", "/subjects/science/light"],
  ["The Human Eye", "5 Marks", "91% Frequent", "bg-violet-50 text-violet-600", "bg-orange-100 text-orange-600", "#"],
  ["Electricity", "7 Marks", "88% Frequent", "bg-amber-50 text-amber-600", "bg-orange-100 text-orange-600", "#"],
] as const;

export default function Dashboard() {
  const [selectedClass, setSelectedClass] = useState("10");
  const [paywall, setPaywall] = useState(false);
  useEffect(() => { const timer = window.setTimeout(() => setPaywall(true), 1500); return () => window.clearTimeout(timer); }, []);
  return <div className="ambient min-h-screen bg-[#f5f7fc] text-slate-900"><Header />
    <main className="mx-auto max-w-7xl px-4 pb-12 pt-7 sm:px-7 sm:pt-10">
      <section className="grid gap-5 lg:grid-cols-[1.45fr_.75fr]">
        <div className="relative overflow-hidden rounded-[28px] bg-[#111827] px-6 py-7 text-white shadow-xl sm:px-9 sm:py-8"><div className="absolute -right-10 -top-16 size-72 rounded-full bg-blue-500/20 blur-2xl"/><div className="absolute bottom-0 right-12 size-32 rounded-full bg-red-500/20 blur-2xl"/><div className="relative"><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-xs font-bold text-blue-100"><Sparkles size={13} className="text-yellow-300"/> PYQ-BASED REVISION</span><h1 className="mt-5 max-w-lg text-3xl font-black leading-tight tracking-tight sm:text-[40px]">Paper kal hai?<br/><em className="not-italic text-[#7db0ff]">Start with the likely patterns.</em></h1><p className="mt-3 max-w-md text-sm leading-6 text-slate-300">AI turns past-question patterns into a focused practice list when you&apos;re short on time.</p><div className="mt-6 flex flex-wrap items-center gap-3"><a href="#subjects" className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-black text-slate-950">Build my revision set <ArrowRight size={16}/></a><span className="text-xs font-semibold text-slate-400">For revision only · no question guarantees</span></div></div></div>
        <div className="rounded-[28px] border border-violet-100 bg-white p-6 shadow-[0_16px_40px_rgba(42,48,90,.06)]"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-xl bg-[#f1edff] text-violet-600"><Trophy size={20}/></span><span className="rounded-full bg-green-50 px-2.5 py-1 text-[10px] font-black text-green-600">ON TRACK</span></div><p className="mt-5 text-sm font-bold text-slate-500">Your Crammer Streak</p><div className="mt-1 flex items-end justify-between"><b className="text-4xl font-black tracking-tight">4 <span className="text-base text-slate-400">days</span></b><div className="flex gap-1">{[1,2,3,4,5,6,7].map(day => <i key={day} className={`block size-3 rounded-full ${day < 5 ? "bg-violet-500" : "bg-slate-100"}`}/>)}</div></div><div className="mt-5 border-t border-slate-100 pt-4 text-xs font-bold text-slate-500">Keep going — you&apos;re <b className="text-violet-600">2 chapters</b> ahead!</div></div>
      </section>
      <section className="mt-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-bold text-blue-600">SET YOUR TARGET</p><h2 className="mt-1 text-2xl font-black tracking-tight">What are you cramming for?</h2></div><p className="text-xs font-semibold text-slate-400">Your picks save automatically</p></div><div className="mt-4 flex gap-2 overflow-x-auto pb-1 hide-scrollbar">{["8","9","10"].map(item => <button onClick={() => setSelectedClass(item)} key={item} className={`min-w-28 rounded-xl border px-5 py-3 text-left text-sm font-black transition ${selectedClass === item ? "border-blue-600 bg-blue-600 text-white shadow-lg shadow-blue-200" : "border-slate-200 bg-white text-slate-500"}`}><span className="block text-[10px] opacity-70">CBSE</span>Class {item}</button>)}</div></section>
      <section id="subjects" className="mt-8"><div className="flex items-center justify-between"><h2 className="text-xl font-black tracking-tight">Pick a subject</h2><button className="inline-flex items-center gap-1 text-xs font-black text-blue-600">View all <ChevronRight size={14}/></button></div><div className="mt-4 grid gap-3 sm:grid-cols-3">{subjects.map(subject => <button key={subject.name} className="group rounded-2xl border border-slate-100 bg-white p-5 text-left shadow-[0_8px_24px_rgba(31,41,55,.04)] transition hover:-translate-y-1 hover:shadow-lg"><span className={`grid size-11 place-items-center rounded-xl text-2xl font-bold ${subject.color}`}>{subject.icon}</span><h3 className="mt-4 font-black">{subject.name}</h3><div className="mt-1 flex justify-between text-xs font-semibold text-slate-400"><span>{subject.chapters} chapters</span><span className="text-red-500">{subject.hot}</span></div></button>)}</div></section>
      <section className="mt-9 grid gap-6 xl:grid-cols-[1fr_310px]"><div><div className="flex items-center justify-between"><div><p className="text-sm font-bold text-green-600">SCIENCE · CLASS {selectedClass}</p><h2 className="mt-1 text-xl font-black tracking-tight">High-yield chapters</h2></div><button className="rounded-xl bg-white px-3 py-2 text-xs font-bold text-slate-500 shadow-sm">Sort: Exam weightage</button></div><div className="mt-4 space-y-3">{chapters.map(([title, marks, hot, iconBg, tagBg, href], i) => <Link href={href} key={title} className="group flex items-center gap-3 rounded-2xl border border-slate-100 bg-white p-3 shadow-sm transition hover:border-blue-200 hover:shadow-md sm:p-4"><span className={`grid size-11 shrink-0 place-items-center rounded-xl ${iconBg}`}><BookOpen size={20}/></span><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-black sm:text-base">{title}</h3><div className="mt-1 flex flex-wrap gap-2"><span className="text-[11px] font-bold text-slate-400">{marks}</span><span className={`rounded px-1.5 py-0.5 text-[10px] font-black ${tagBg}`}>{i === 0 && <Flame className="mr-0.5 inline" size={10}/>} {hot}</span></div></div><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-slate-50 text-slate-400 transition group-hover:bg-blue-600 group-hover:text-white"><ChevronRight size={18}/></span></Link>)}</div></div>
      <aside id="crammer" className="relative overflow-hidden rounded-[26px] bg-gradient-to-br from-[#6950d9] to-[#31238e] p-6 text-white shadow-xl"><div className="absolute -right-10 -top-8 size-40 rounded-full bg-pink-400/30 blur-xl"/><LockKeyhole size={24} className="relative text-yellow-300"/><p className="relative mt-4 text-xs font-bold tracking-widest text-violet-200">CRAMMER PASS</p><h2 className="relative mt-2 text-2xl font-black leading-tight">All the high-yield.<br/>None of the panic.</h2><p className="relative mt-3 text-sm leading-5 text-violet-100">Unlock every predicted question for your exams this week.</p><ul className="relative mt-5 space-y-2 text-xs font-semibold text-violet-100"><li><Check className="mr-2 inline text-yellow-300" size={14}/>10-year CBSE pattern data</li><li><Check className="mr-2 inline text-yellow-300" size={14}/>Step-by-step mark schemes</li><li><Check className="mr-2 inline text-yellow-300" size={14}/>Bhai/Didi AI tutor</li></ul><button onClick={() => setPaywall(true)} className="relative mt-6 w-full rounded-xl bg-white px-4 py-3 text-sm font-black text-violet-800">Unlock for ₹50 <span className="font-medium opacity-60">/ 7 days</span></button></aside></section>
    </main><button onClick={() => setPaywall(true)} className="fixed bottom-5 right-5 z-30 grid size-14 place-items-center rounded-2xl bg-[#ef4444] text-white shadow-xl shadow-red-300" aria-label="Ask Bhai Didi"><Bot size={25}/><i className="absolute right-1 top-1 size-3 rounded-full border-2 border-white bg-green-400"/></button>{paywall && <Paywall onClose={() => setPaywall(false)} />}</div>;
}
function Paywall({ onClose }: { onClose: () => void }) { return <div className="fixed inset-0 z-50 grid place-items-end bg-slate-950/50 p-0 backdrop-blur-sm sm:place-items-center sm:p-4"><div className="relative w-full max-w-md rounded-t-[30px] bg-white p-7 shadow-2xl sm:rounded-[30px]"><button onClick={onClose} aria-label="Close" className="absolute right-5 top-5 text-slate-400"><X size={20}/></button><span className="grid size-12 place-items-center rounded-2xl bg-red-50 text-red-500"><Flame size={25}/></span><p className="mt-5 text-xs font-black tracking-widest text-red-500">GYQ CRAMMER PASS</p><h2 className="mt-2 text-3xl font-black tracking-tight">Paper kal hai?<br/>Let&apos;s make a plan.</h2><div className="mt-3 rounded-xl bg-amber-50 px-3 py-2 text-xs font-bold text-amber-800">“Cha cha, padhai nahi ki… ab PYQ pattern dekh le.” 😭</div><p className="mt-3 text-sm leading-6 text-slate-500">Focused AI practice from PYQ patterns — not leaked papers, and never a guarantee of exam questions.</p><div className="mt-5 rounded-2xl bg-slate-50 p-4"><p className="text-3xl font-black">₹50 <span className="text-sm font-bold text-slate-400">for 7 days</span></p><p className="mt-1 text-xs font-semibold text-slate-500">UPI, card or net banking · powered by Razorpay</p></div><button onClick={onClose} className="mt-5 w-full rounded-xl bg-blue-600 py-3.5 text-sm font-black text-white shadow-lg shadow-blue-200">Pay ₹50 via UPI / Card</button><p className="mt-3 text-center text-[11px] font-medium text-slate-400">No subscription. Just exam-time access.</p></div></div>; }
